cmake_minimum_required(VERSION 2.8.3)

file(READ "${CMAKE_CURRENT_LIST_DIR}/../src/surfels_unknown_space.cl" CL_PROGRAM)
file(WRITE "${CMAKE_CURRENT_LIST_DIR}/../src/surfels_unknown_space.cl.h" "// Generated by surfels_unknown_space_cl.cmake\n// from surfels_unknown_space.cl\n#include <string>\n static const std::string SURFELS_UNKNOWN_SPACE_CL = R\"4082c6f8(${CL_PROGRAM})4082c6f8\";")
